server:
  port: 8085

logging:
  path: logs/
  level:
    root: INFO

spring:
  profiles.active: mysql,dev,elasticsearch,webpower
  messages:
    basename: cn/tendata/mdcs/messages,cn/tendata/mdcs/web/messages,i18n/admin/ValidationMessages
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      jadira.usertype.autoRegisterUserTypes: true
    hibernate:
      naming-strategy: cn.tendata.mdcs.data.jpa.config.CustomNamingStrategy
      ddl-auto: validate
  thymeleaf:
      enabled: true
      cache: false
      mode: LEGACYHTML5

security:
  ignored: /favicon.ico,css/**,/js/**,/fonts/**,/img/**,/webjars/**,/admin/app/**,/admin/assets/**,/admin/css/**,/admin/html/**,/admin/images/**

multipart:
  enabled: true
  max-file-size: 1Mb
  max-request-size: 10Mb

link:
  accounts.root: ${accounts.server.name:http://localhost:8080/accounts}
  wmt.root: ${wmt.server.name:http://localhost:8080/wmt}
  contactx.root: ${cx.server.name:http://localhost:8080/contactx}
  pay.root: ${pay.server.name:http://localhost:8888/pay}
  wenda.root: ${wenda.server.name:http://localhost:8087}
  analysis.root: ${analysis.server.name:http://localhost:8089}


filter:
    mailRecipient-uri: ${link.analysis.root}/api/analysis/filter/verify?mailRecipients={mailRecipients}&callVersion=1.0


payment:
  gateway-uri: ${pay.server.name:https://localhost:8888}/api/gateway
  partner: 111111
  key: 111111
  notify-url: ${edm.server.name:http://localhost:${server.port}}/pay/notify

---
spring:
  profiles: cas
cas:
  service: ${edm.server.name:http://localhost:${server.port}}/login/cas
  server-url-prefix: ${cas.server.name:http://192.168.0.100:8080/cas}
  server-login-url:  ${cas.server-url-prefix}/login
  server-logout-url:  ${cas.server-url-prefix}/logout
  application-parameters.applicationId: 1006
  application-parameters.hasChildUsers: true
---
spring:
  profiles: mysql
  datasource:
    driver-class-name: ${datasource.driver-class-name:com.mysql.jdbc.Driver}
    url: ${datasource.url:jdbc:mysql://192.168.37.128:3306/spring-boot-frame}
    username: ${datasource.username:root}
    password: ${datasource.password:}
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
flyway:
  locations: classpath:db/migration/mysql

---
spring:
  profiles: elasticsearch
  data:
    elasticsearch:
      cluster-name: dev-es-cluster
      cluster-nodes: 192.168.0.62:9300
---
spring:
  profiles: webpower
batch:
  sftp-host: ${batch.sftp-url:210.14.71.141}
  sftp-login-user: ${batch.sftp-login-username:webpowersftp}
  sftp-login-password: ${batch.sftp-login-passwd:webpowersftp}
  sftp-port: ${batch.port:22626}
  sftp-dir-remote-download: ${batch.sftp-remote-download:download}
  sftp-dir-remote-upload: ${batch.sftp-remote-upload:upload}
  local-dir-perefix: ${batch.local-download-directory:/data/sftp/webpowerftp}

---
spring:
  batch:
    job:
      enabled: false

