CREATE TABLE COM_AUDIT_TRAIL
(
    AUD_USER      VARCHAR(100)  NOT NULL,
    AUD_CLIENT_IP VARCHAR(15)    NOT NULL,
    AUD_SERVER_IP VARCHAR(15)    NOT NULL,
    AUD_RESOURCE  VARCHAR(255)  NOT NULL,
    AUD_ACTION    VARCHAR(100)  NOT NULL,
    APPLIC_CD     VARCHAR(50)    NOT NULL,
    AUD_DATE      DATETIME      NOT NULL
);
 
ALTER TABLE COM_AUDIT_TRAIL
ADD CONSTRAINT COM_AUDIT_TRAIL_PK
PRIMARY KEY (
    AUD_USER,
    AUD_CLIENT_IP,
    AUD_SERVER_IP,
    AUD_RESOURCE,
    AUD_ACTION,
    APPLIC_CD,
    AUD_DATE
);

CREATE TABLE COM_STATISTICS
(
    STAT_SERVER_IP VARCHAR(15)  NOT NULL,
    STAT_DATE      DATE          NOT NULL,
    APPLIC_CD      VARCHAR(50)   NOT NULL,
    STAT_PRECISION VARCHAR(6)   NOT NULL,
    STAT_COUNT     NUMERIC      NOT NULL,
    STAT_NAME      VARCHAR(100) NOT NULL
);

ALTER TABLE COM_STATISTICS
ADD CONSTRAINT COM_STATISTICS_PK
PRIMARY KEY (
    STAT_SERVER_IP,
    STAT_DATE,
    APPLIC_CD,
    STAT_PRECISION,
    STAT_NAME
);

CREATE INDEX COM_AUDIT_TRAIL_DATE_I ON COM_AUDIT_TRAIL (AUD_DATE);
CREATE INDEX COM_AUDIT_TRAIL_CLIENT_DATE_I ON COM_AUDIT_TRAIL (AUD_CLIENT_IP, AUD_DATE);
CREATE INDEX COM_AUDIT_TRAIL_USER_DATE_I ON COM_AUDIT_TRAIL (AUD_USER, AUD_DATE);
CREATE INDEX COM_AUDIT_TRAIL_ACTION_DATE_I ON COM_AUDIT_TRAIL (AUD_ACTION, AUD_DATE);
CREATE INDEX COM_STATISTICS_DATE_I ON COM_STATISTICS (STAT_DATE);
CREATE INDEX COM_STATISTICS_NAME_DATE_I ON COM_STATISTICS (STAT_NAME, STAT_DATE);